yatube/about/urls.py
from about.views import AboutAuthorView, AboutTechView
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index',),
    path('follow/', views.follow_index, name='follow_index',),
    path('create/', views.post_create, name='post_create',),
    path('profile/<str:username>/', views.profile, name='profile',),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail',),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit',),
    path(
        'posts/<int:post_id>/comment/',
        views.post_comment,
        name='post_comment',
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/head.html
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="/static/img/fav/fav.ico" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="/static/img/fav/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/static/img/fav/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/static/img/fav/favicon-16x16.png">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="/static/img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>        
    <ul class="nav  nav-pills">
      <li class="nav-item">              
        <a class="nav-link" href="{% url 'about:author' %}">
          Об авторе
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about:tech' %}">
          Технологии
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'posts:post_create' %}">
          Новая запись
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light " href="../users/password_change_form.html">
          Изменить пароль
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
      </li>
      <li class="mt-2">
        Пользователь: {{  user  }}
      <li>
      <li class="nav-item"> 
        <a class="nav-link link-light" href="{% url 'users:login' %}">
          Войти
        </a>
      </li>
      <li class="nav-item"> 
        <a class="nav-link link-light " href="{% url 'users:signup' %}">Регистрация</a>
      </li>
    </ul>      
  </div>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:post_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %}

yatube/templates/includes/post_item.html
{% load thumbnail %}

<article>
  <ul>
    <li>
      Автор: {{  post.author  }}
      <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{  post.pub_date |date:"d E Y" }} 
    </li>
  </ul>

  {% thumbnail post.image '960x339' crop='center' upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}" width={{ im.width }} height={{ im.height }}>
  {% endthumbnail %}

  <p>
    {{  post.text  }}
  </p>

  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
</article>

{% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}

{% if not forloop.last %}<hr>{% endif %}  

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}