yatube/about/urls.py
from about.views import AboutAuthorView, AboutTechView
from django.urls import path

app_name = 'about'

urlpatterns = [
    path('author/', AboutAuthorView.as_view(), name='author'),
    path('tech/', AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index',),
    path('follow/', views.follow_index, name='follow_index',),
    path('create/', views.post_create, name='post_create',),
    path('profile/<str:username>/', views.profile, name='profile',),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow',
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow',
    ),
    path('group/<slug:slug>/', views.group_list, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail',),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit',),
    path(
        'posts/<int:post_id>/comment/',
        views.post_comment,
        name='post_comment',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст статьи',
        help_text='Введите текст статьи',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        help_text='Укажите дату публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор статьи',
        help_text='Укажите автора статьи',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа статей',
        help_text='Выберите тематическую группу '
                  'в выпадающем списке по желанию',
    )
    image = models.ImageField(
        verbose_name='Картинка статьи',
        help_text='Добавьте картинку статьи',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text='Введите название тематической группы',
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Номер группы',
        help_text='Укажите порядковый номер группы',
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Добавьте текст описания группы',
    )

    class Meta:
        verbose_name = 'Группа статей'
        verbose_name_plural = 'Группы статей'
        ordering = ('-title',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Имя поста',
        help_text='Укажите имя поста',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Имя автора',
        help_text='Укажите автора',
    )
    text = models.TextField(
        max_length=300,
        verbose_name='Текст комментария',
        help_text='Укажите текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата комментария',
        help_text='Укажите дату комментария',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self) -> str:
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Укажите подписчика',
        help_text='Подписчик',
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        verbose_name='Укажите на кого подписываемся',
        help_text='Автор поста',
    )

    class Meta:
        ordering = ('-user',)
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_follows',
            ),
        )

    def __str__(self) -> str:
        return f'{self.user.username} подписан на {self.author.username}'

yatube/posts/forms.py
from django import forms
from posts.models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 7}),
            'group': forms.Select(attrs={'class': 'form-control'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 7}),
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from posts.forms import CommentForm, PostForm
from posts.models import Follow, Group, Post

User = get_user_model()


def index(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    followers = Follow.objects.filter(author__username=username).count()
    context = {
        'author': author,
        'page_obj': page_obj,
        'followers': followers,
        'following': False,
    }
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=author, user=request.user
        ).exists()
        context.update({
            'following': following,
            'user': request.user,
        })
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST)
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'paginator': paginator,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@login_required
def post_create(request):
    form = PostForm(data=request.POST, files=request.FILES)

    if request.method != 'POST':
        form = PostForm()
        return render(request, 'posts/post_create.html', {'form': form})

    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})

    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        data=request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def post_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'paginator': paginator,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(
            user=user,
            author=author,
        )
    return redirect(reverse('posts:profile', kwargs={'username': username}))


@login_required
def profile_unfollow(request, username):
    unfollow = Follow.objects.select_related('user').filter(
        user=request.user,
        author__username=username,
    )
    if unfollow.exists():
        unfollow.delete()
    return redirect(reverse('posts:profile', kwargs={'username': username}))

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% cache 20 index_page %}
  {% load thumbnail %}

  {% block title %}
    Подписки пользователей
  {% endblock %}

  {% block content %}
    <div class="container py-5">        
      <h1>Посты на авторов которых вы подписаны</h1>
        {% include 'includes/switcher.html' %}
        {% for post in page_obj %}
            {% include "includes/post_item.html" with post=post %}
            {% if not forloop.last %}<hr>{% endif %}  
        {% endfor %}
        
        {% if page_obj.has_other_pages %}
        {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
        {% endif %}
      </div>
  {% endblock content %}

{% endcache %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{  group.title  }}
{% endblock %}

{% block content %}
      <div class="container py-5">        
        <h1>{{  group.title  }}</h1>
        <p>{{  group.description  }}</p>
        {% for post in page_obj %}
            {% include "includes/post_item.html" with post=post %}
        {% endfor %}
        {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
        {% endif %}
      </div>
      
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
<div class="container py-5">        
  <h1>Все посты</h1>

  {% include 'includes/switcher.html' %}

  {% cache 20 index_page %}

    {% for post in page_obj %}
      {% include "includes/post_item.html" with post=post %}
      {% if not forloop.last %}<hr>{% endif %}  
    {% endfor %}
      
    {% if page_obj.has_other_pages %}
      {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
    {% endif %}

  {% endcache %}

</div>

{% endblock content %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %} {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block header %} {% if is_edit %} Редактировать запись {% else %} Добавить запись {% endif %} {% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Создать статью
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary btn-block">{% if is_edit %}Сохранить{% else %}Добавить запись{% endif %}</button>
          </div>
          </form>
        </div>
      </div>
    </div>
</div> 

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {{  post.text  }}
{% endblock %}

{% block content %}
<div class="container py-5">
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{  post.pub_date |date:"d E Y"  }}
              </li>
              {% if post.group %}
                <li class="list-group-item">
                  Группа: {{  post.group  }}
                  <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                  </a>
                </li>            
              {% endif %}              
              <li class="list-group-item">
                Автор: {{  post.author  }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ user.posts.all.count }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                  Все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
              редактировать запись
            </a>

            {% include 'includes/post_comment.html' %}
            
          </article>
        </div>     
      </div>      
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{  author  }}{% endblock title %}

{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{  author  }}</h1>
    <h3>Всего постов: {{  author.posts.all.count  }}</h3>
    <h3>Всего подписчиков: {{  followers  }}</h3>

      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
    
      {% for post in page_obj %}
            {% include "includes/post_item.html" with post=post %}
      {% endfor %}

      {% if page_obj.has_other_pages %}
            {% include "includes/paginator.html" with page_obj=page_obj paginator=paginator%}
      {% endif %}
  </div>
{% endblock content %}